apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: single-tier-hpa
  labels:
    app: single-tier
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: single-tier
  minReplicas: 1
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 1
