global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'stackdriver-exporter'
    honor_labels: true # Important to keep labels (like function_name)
    static_configs:
      - targets: ['stackdriver-exporter:9255']

  - job_name: 'kube-state-metrics'
    static_configs:
    - targets: ['gke-cluster-ksm:8080']